# Autonomous Bicycle - Python Enviorment

# Base image of container
FROM python:3.10.6-slim

# Set working directory of container
WORKDIR /usr/app/

# Install pip dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# X11 Server Content
RUN apt-get update
RUN apt-get install -y tk       # Required by Matplotlib for GUI
RUN apt-get install python-gdal # Required by OSMNX

# This stuff is not needed?
# ENV DISPLAY host.docker.internal:0
# RUN apt-get install -y x11-apps

# Run on container start (not when using docker-compose run, however)
CMD [ "python", "main.py" ]
