<?xml version="1.0"?>
<package format="3">
  <name>purepursuit</name>
  <version>0.1.0</version>
  <description>Pure pursuit algorithm.</description>
  <maintainer email="khz8@cornell.edu">Kelly Zhang</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
