/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cyberbotics.webots.controller;

public class VacuumGripper extends Device {
  private transient long swigCPtr;

  protected VacuumGripper(long cPtr, boolean cMemoryOwn) {
    super(wrapperJNI.VacuumGripper_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VacuumGripper obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        wrapperJNI.delete_VacuumGripper(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public VacuumGripper(String name) {
    this(wrapperJNI.new_VacuumGripper(name), true);
  }

  public void enablePresence(int samplingPeriod) {
    wrapperJNI.VacuumGripper_enablePresence(swigCPtr, this, samplingPeriod);
  }

  public void disablePresence() {
    wrapperJNI.VacuumGripper_disablePresence(swigCPtr, this);
  }

  public int getPresenceSamplingPeriod() {
    return wrapperJNI.VacuumGripper_getPresenceSamplingPeriod(swigCPtr, this);
  }

  public boolean getPresence() {
    return wrapperJNI.VacuumGripper_getPresence(swigCPtr, this);
  }

  public boolean isOn() {
    return wrapperJNI.VacuumGripper_isOn(swigCPtr, this);
  }

  public void turnOn() {
    wrapperJNI.VacuumGripper_turnOn(swigCPtr, this);
  }

  public void turnOff() {
    wrapperJNI.VacuumGripper_turnOff(swigCPtr, this);
  }

}
